project_id = "cstxrauedasufcecaouq"

[functions.create-test-artisan]
verify_jwt = false

[functions.generate-seo-description]
verify_jwt = false

[functions.generate-portfolio-caption]
verify_jwt = false

[functions.create-artisan-account]
verify_jwt = false

[functions.send-project-request-email]
verify_jwt = false

[functions.generate-faq]
verify_jwt = false

[functions.generate-expert-faq]
verify_jwt = false

[functions.ask-expert-andrea]
verify_jwt = false

[functions.ask-expert-andrea-stream]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
