project_id = "nkeodfivjnhawzrezuqp"

[functions.send-security-notification]
verify_jwt = false

[functions.cleanup-expired-stories]
verify_jwt = false

[functions.send-subscription-notification]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.admin-delete-waiting-artisan]
verify_jwt = false

[functions.admin-delete-client]
verify_jwt = false

[functions.get-subscription-details]
verify_jwt = false

[functions.delete-artisan-account]
verify_jwt = false

[functions.delete-client-account]
verify_jwt = false
