-- Update public_artisans view to include pending status for public visibility
CREATE OR REPLACE VIEW public.public_artisans AS
SELECT 
  a.id,
  a.business_name,
  a.description,
  a.city,
  a.department,
  a.region,
  a.address,
  a.postal_code,
  a.phone,
  a.email,
  a.photo_url,
  a.portfolio_images,
  a.portfolio_videos,
  a.category_id,
  a.rating,
  a.review_count,
  a.experience_years,
  a.hourly_rate,
  a.is_verified,
  a.missions_completed,
  a.status,
  a.working_hours,
  a.qualifications,
  a.facebook_url,
  a.instagram_url,
  a.linkedin_url,
  a.website_url,
  a.slug,
  a.google_id,
  a.google_maps_url,
  a.google_rating,
  a.google_review_count,
  a.created_at,
  a.updated_at,
  a.subscription_tier,
  a.display_priority,
  a.latitude,
  a.longitude,
  a.intervention_radius
FROM artisans a
WHERE a.status IN ('active'::artisan_status, 'prospect'::artisan_status, 'pending'::artisan_status);